routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SkimController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\PembekalController;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\TuntutanController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\TuntutanPrintController;

Route::get('/pwd', function() {
    return \Hash::make('1234');
});

Route::redirect('/', '/login');

// Fungsi authentication
Route::get('login', [LoginController::class, 'borangLogin'])->name('login');
Route::post('login', [LoginController::class, 'authenticate'])->name('login.authenticate');

// Ruangan pengguna selepas login
Route::group(['middleware' => 'auth'], function () {

    Route::get('dashboard', fn() => view('dashboard'))->name('dashboard');

    // Module Pengguna
    Route::any('pengguna', [PenggunaController::class, 'paparSenarai'])->name('users.index');
    Route::get('pengguna/{id}/detail', [PenggunaController::class, 'paparDetail'])->name('users.detail');
    Route::get('pengguna/daftar', [PenggunaController::class, 'paparBorangDaftar'])->name('users.create');
    Route::post('pengguna/daftar', [PenggunaController::class, 'terimaDataPendaftaran'])->name('users.store');
    Route::post('pengguna/{id}', [PenggunaController::class, 'paparPengguna'])->name('users.show');
    Route::get('pengguna/{id}/edit', [PenggunaController::class, 'paparBorangEdit'])->name('users.edit');
    Route::get('pengguna/{id}', [PenggunaController::class, 'terimaDataEdit'])->name('users.update');
    Route::delete('pengguna/{id}', [PenggunaController::class, 'hapusData'])->name('users.destroy');

    // Module Pembekal
    Route::get('pembekal', [PembekalController::class, 'paparSenarai'])->name('pembekal.index');
    Route::get('pembekal/daftar', [PembekalController::class, 'paparBorangDaftar'])->name('pembekal.create');
    Route::post('pembekal/daftar', [PembekalController::class, 'terimaDataPendaftaran'])->name('pembekal.store');
    Route::post('pembekal/{id}', [PembekalController::class, 'paparPembekal'])->name('pembekal.show');
    Route::get('pembekal/{id}/edit', [PembekalController::class, 'paparBorangEdit'])->name('pembekal.edit');
    Route::get('pembekal/{id}', [PembekalController::class, 'terimaDataEdit'])->name('pembekal.update');
    Route::delete('pembekal/{id}', [PembekalController::class, 'hapusData'])->name('pembekal.destroy');

    // Module Skim
    Route::get('skim', [SkimController::class, 'paparSenarai'])->name('skim.index');
    Route::get('skim/daftar', [SkimController::class, 'paparBorangDaftar'])->name('skim.create');
    Route::post('skim/daftar', [SkimController::class, 'terimaDataPendaftaran'])->name('skim.store');
    Route::post('skim/{id}', [SkimController::class, 'paparSkim'])->name('skim.show');
    Route::get('skim/{id}/edit', [SkimController::class, 'paparBorangEdit'])->name('skim.edit');
    Route::get('skim/{id}', [SkimController::class, 'terimaDataEdit'])->name('skim.update');
    Route::delete('skim/{id}', [SkimController::class, 'hapusData'])->name('skim.destroy');

    // Module Tuntutan
    Route::post('tuntutan/datatables', [TuntutanController::class, 'datatables'])->name('tuntutan.datatables');
    Route::get('tuntutan/daftar', [TuntutanController::class, 'paparBorangDaftar'])->name('tuntutan.create');
    Route::post('tuntutan/daftar', [TuntutanController::class, 'terimaDataPendaftaran'])->name('tuntutan.store');
    Route::get('tuntutan/{id}/edit', [TuntutanController::class, 'paparBorangEdit'])->name('tuntutan.edit');
   // Route::get('tuntutan/{id}', [TuntutanController::class, 'terimaDataEdit'])->name('tuntutan.update');
    Route::get('tuntutan/{tuntutan}/print', [TuntutanPrintController::class, 'print'])->name('tuntutan.print');

    Route::resource('tuntutan', TuntutanController::class);

    Route::get('logout', [LogoutController::class, 'logout'])->name('logout');

    Route::get('sub-pembekal/{pembekal_id}', [PembekalController::class, 'subPembekal']);

    Route::any('laporan-tuntutan',
    [LaporanController::class, 'tuntutan']);

});

app/Models/Tuntutan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tuntutan extends Model
{
    use HasFactory;

    protected $table = 'tuntutan';

    protected $fillable = [
        'no_fail',
        'skim_id',
        'pembekal_id',
        'tahun',
        'tarikh_tuntutan',
        'jumlah_tuntutan',
        'jumlah_peruntukan',
        'baki_peruntukan',
        'kuota',
    ];

    // Status tuntutan
    public const STATUS_TUNTUTAN_BARU = 'Tuntutan Baru';
    //public const STATUS_SEMAKAN_TUNTUTAN = 'Semakan Tuntutan';
    public const STATUS_PENYEDIAAN_PERAKUAN = 'Semakan Tuntutan';
    public const STATUS_SEMAKAN_SEMULA = 'Semakan Semula';
    public const STATUS_TERIMAAN_SEMULA_TUNTUTAN = 'Terimaan Semula Tuntutan';
    public const STATUS_PERAKUAN_TUNTUTAN = 'Perakuan Tuntutan';
    public const STATUS_SAH_PERAKUAN = 'Sah Perakuan';
    public const STATUS_TIDAK_SAH_PERAKUAN = 'Sah Perakuan';
    public const STATUS_TERIMAAN_SEMULA_PERAKUAN = 'Terimaan Semula Perakuan';
    public const STATUS_TERIMAAN_SEMULA_SAH_PERAKUAN = 'Terimaan Semula Sah Perakuan';
    public const STATUS_SEMAKAN_KEWANGAN = 'Semakan Kewangan';
    public const STATUS_BAYARAN_SELESAI = 'Bayaran Selesai';

    // Tuntutan mempunyai banyak panel dari table tuntutan_panels
    public function panel()
    {
        return $this->hasMany(TuntutanPanel::class);
    }

    // Tuntutan mempunyai banyak panel dari table tuntutan_statuses
    public function status()
    {
        return $this->hasMany(TuntutanStatus::class);
    }

    public function pembekal()
    {
        return $this->belongsTo(Pembekal::class);
    }

    public function skim()
    {
        return $this->belongsTo(Skim::class);
    }
}

app/Http/Controllers/TuntutanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Skim;
use App\Models\Tuntutan;
use App\Models\User;
use App\Models\Ref;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\DataTables;

class TuntutanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('permission:superadmin.all.areas|tuntutan.view', ['only' => ['paparSenarai']]);
        $this->middleware('permission:superadmin.all.areas|tuntutan.create', ['only' => ['paparBorangDaftar', 'terimaDataPendaftaran']]);
        $this->middleware('permission:superadmin.all.areas|tuntutan.edit', ['only' => ['paparBorangEdit', 'terimaDataEdit']]);
        $this->middleware('permission:superadmin.all.areas|tuntutan.delete', ['only' => ['hapusData']]);
    }

    // champs.test/tuntutan
    public function index() {
        $status = Ref::where('cat', 'sts-tuntutan')->pluck('descr', 'code');
        $sql = "SELECT t.no_rujukan_fail, t.jum_tuntutan, t.tkh_tuntutan, pp.jum_kontrak, s.nama, t.status
                FROM tuntutan t, penyaluran_pembekal pp, penyaluran p, skim s
                WHERE t.pp_id = pp.id and pp.penyaluran_id = p.id AND p.skim_id = s.id";
        $rows = \DB::select($sql);
        //dd($rows);
        return view('tuntutan.listing', compact('rows', 'status'));
    }

    public function datatables()
    {
        $query = Tuntutan::query()->with('pembekal', 'skim');
        return DataTables::of($query)
            ->addColumn('tindakan', function ($tuntutan) {
                return view('tuntutan.datatables-tindakan', compact('tuntutan'));
            })
            ->make(true);
    }

    public function create()
    {
        //$senaraiPembekal = Pembekal::select('id', 'nama')->get();
        $rows = \DB::select("SELECT pp.id, p.nama FROM penyaluran_pembekal pp, pembekal p WHERE pp.pembekal_id = p.id");
        $senaraiPembekal = [];
        foreach ($rows as $row) {
            $senaraiPembekal[$row->id] = $row->nama;
        }
        $senaraiSkim = Skim::select('id', 'nama')->get();
        $senaraiPanel = User::select('id', 'nama')->get();
        return view('tuntutan.create', compact('senaraiPembekal', 'senaraiSkim', 'senaraiPanel'));
    }

    public function store(Request $request)
    {
        $tuntutan = new Tuntutan();
        $tuntutan->pp_id = $request->pp_id;
        $tuntutan->jum_tuntutan = $request->jum_tuntutan;
        $tuntutan->tkh_tuntutan = $request->tkh_tuntutan;
        $tuntutan->penyemak_id = $request->penyemak_id;
        $tuntutan->no_rujukan_fail = $request->no_rujukan_fail;
        $tuntutan->status = 1; //Baru
        $tuntutan->save();
        return redirect()->route('tuntutan.index')->with('alert-success', 'Rekod berjaya ditambah');
    }

//Simpan daftar tuntutan
    public function terimaDataPendaftaran(Request $request)
    {
        // Proses validasi dan dapatkan semua data yang di-validate
        $data = $request->validate([
            'no_fail' => ['min:3'],
            'skim_id' => ['min:3'],
            'pembekal_id' => ['min:3'],
            'tahun' => ['integer'],
            'tarikh_tuntutan' => ['min:3'],
            'tarikh_tuntutan_baru' => ['min:3'],
            'jumlah_peruntukan' => ['min:3'],
            'baki_peruntukan' => ['min:3'],
            'kuota' => ['min:3'],

        ]);

        // Beri response redirect ke senarai skim
        return redirect()->route('tuntutan.index')
            ->with('alert-success', 'Rekod berjaya ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Tuntutan  $tuntutan
     * @return \Illuminate\Http\Response
     */
    public function show(Tuntutan $tuntutan)
    {
        if (auth()->user()->hasAnyRole('Ketua Panel BPB', 'Panel BPB')) {
            return view('tuntutan.detail-panel', compact('tuntutan'));
        }

        return view('tuntutan.detail', compact('tuntutan'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tuntutan  $tuntutan
     * @return \Illuminate\Http\Response
     */
    public function paparBorangEdit($id)
    {
        $tuntutan = Tuntutan::findOrFail($id);

        $senaraiTuntutan = Tuntutan::select('id')->get();

        return view('tuntutan.borang-edit', compact('tuntutan'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Tuntutan  $tuntutan
     * @return \Illuminate\Http\Response
     */
    // function terimaDataEdit(Request $request, $id)
    // {
    // Proses validasi dan dapatkan semua data yang di-validate
    //  $data = $request->validate([
    //      'no_fail' => ['min:3'],
    //      'skim_id' => ['min:3'],
    //      'pembekal_id' => ['min:3'],
    //      'tahun' => ['integer'],
    //      'tarikh_tuntutan' => ['min:3'],
    //       'tarikh_tuntutan_baru' => ['min:3'],
    //      'jumlah_peruntukan' => ['min:3'],
    //      'baki_peruntukan' => ['min:3'],
    //      'kuota' => ['min:3'],
    //     'dokumen' => ['min:3'],
    //     'catatan' => ['min:3'],
    //     'semakan_panel' => ['min:3'],

    //  ]);

    // Kemaskini data ke dalam table skim
    //  $tuntutan = tuntutan::findOrFail($id);
    //  $tuntutan->update($id);

    // Beri response redirect ke senarai skim
    //   return redirect()->route('tuntutan.index')
    //   ->with('alert-success', 'Rekod berjaya dikemaskini');
    // }

    public function update(Request $request, Tuntutan $tuntutan)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tuntutan  $tuntutan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tuntutan $tuntutan)
    {
        //
    }
}

resources/views/tuntutan/borang-edit.blade.php
@extends('layouts.induk')

@section('content-utama')

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0">Detail Tuntutan</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
            <li class="breadcrumb-item active">Detail Tuntutan</li>
            </ol>
        </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<section class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">

                <form method="GET" action="{{ route('tuntutan.edit', $tuntutan->id) }}">
                    @csrf

                    <div class="card">
                        <div class="card-body">

                            <div class="row">

                                <div class="col-md-6">

                                    <div class="mb-3">
                                        <label class="form-label">NO. RUJUKAN FAIL TUNTUTAN</label>
                                        <input type="text" class="form-control" name="no_fail" value="{{ $tuntutan->no_fail }}" disabled>
                                    </div>

                                </div>
                                <div class="col-md-6">

                                    <div class="mb-3">
                                        <label class="form-label">NAMA PEMBEKAL</label>
                                        <input type="text" class="form-control" value="{{ $tuntutan->pembekal->nama }}" disabled>
                                    </div>

                                </div>

                            </div>

                            <div class="row">


                                <div class="col-md-6">

                                    <div class="mb-3">
                                        <label class="form-label">NAMA PROGRAM/SKIM</label>
                                        <input type="text" class="form-control" value="{{ $tuntutan->skim->nama }}" disabled>
                                    </div>

                                </div>

                                <div class="col-md-6">

                                    <div class="mb-3">
                                        <label class="form-label">TAHUN</label>
                                        <input type="number" class="form-control" disabled value="{{ $tuntutan->tahun }}">
                                    </div>

                                </div>

                            </div>

                            <div class="row">

                                <div class="col-md-6">

                                    <div class="mb-3">
                                        <label class="form-label">TARIKH TUNTUTAN</label>
                                        <input type="date" class="form-control" name="tarikh_tuntutan" value="{{ $tuntutan->tarikh_tuntutan }}">
                                    </div>

                                </div>

                                <div class="col-md-6">

                                    <div class="mb-3">
                                        <label class="form-label">TARIKH TUNTUTAN BARU</label>
                                        <input type="date" class="form-control" name="tarikh_tuntutan_baru" value="{{ $tuntutan->tarikh_tuntutan_baru }}">
                                    </div>

                                </div>


                                <div class="col-md-6">

                                    <div class="mb-3">
                                        <label class="form-label">JUMLAH TUNTUTAN (RM)</label>
                                        <input type="number" class="form-control" name="jumlah_tuntutan" value="{{ $tuntutan->jumlah_tuntutan }}">
                                    </div>

                                </div>

                            </div>

                            <div class="row">

                                <div class="col-md-4">

                                    <div class="mb-3">
                                        <label class="form-label">JUMLAH PERUNTUKAN (RM)</label>
                                        <input type="number" class="form-control" value="{{ $tuntutan->jumlah_peruntukan }}" disabled>
                                    </div>

                                </div>

                                <div class="col-md-4">

                                    <div class="mb-3">
                                        <label class="form-label">BAKI PERUNTUKAN (RM)</label>
                                        <input type="number" class="form-control " value="{{ $tuntutan->baki_peruntukan }}" disabled>
                                        @error('baki_peruntukan')
                                        <div class="invalid-feedback">
                                            {{ $message }}.
                                        </div>
                                        @enderror
                                    </div>

                                </div>

                                <div class="col-md-4">

                                    <div class="mb-3">
                                        <label class="form-label">KUOTA (RM)</label>
                                        <input type="number" class="form-control" value="{{ $tuntutan->kuota }}" disabled>
                                        @error('jumlah_tuntutan')
                                        <div class="invalid-feedback">
                                            {{ $message }}.
                                        </div>
                                        @enderror
                                    </div>

                                </div>
                            </div>

                            <div class="row">
                                <!-- Status -->
                                <hr>

                                    <table class="table table-bordered">

                                        <thead>
                                            <tr>
                                                <th>STATUS</th>
                                            </tr>
                                        </thead>

                                    <tbody>
                                        @forelse ($tuntutan->status as $status)
                                        <tr>
                                            <td>{{ $status->status }}</td>
                                        </tr>
                                        @empty
                                        <tr>
                                            <td>TIADA REKOD</td>
                                        </tr>
                                         @endforelse
                                    </tbody>

                                    </table>
                                </hr>   
                            </div>
                            <div class="row">
                            <!-- Semakan panel -->
                                <div class="col-md-4">

                                <div class="mb-3">
                                    <label class="form-label">SEMAKAN PANEL</label>

                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="status" value="DOKUMEN LENGKAP" {{ old('status') == 1 ? 'checked' : NULL }}>
                                        <label class="form-check-label">
                                        DOKUMEN LENGKAP
                                        </label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="status" value="DOKUMEN TIDAK LENGKAP" {{ old('status') == 0 ? 'checked' : NULL }}>
                                        <label class="form-check-label">
                                        DOKUMEN TIDAK LENGKAP
                                        </label>
                                    </div>

                                </div>

                            </div>

                                <div class="col-md-4">

                                    <div class="mb-3">
                                        <label class="form-lebel">SENARAI DOKUMEN SOKONGAN</label>
                                        <textarea class="form-control" name="dokumen" value="{{ $tuntutan->dokumen }}"> </textarea>
                                    </div>
                                </div>
                            

                            <div class="col-md-4">

                                <div class="mb-3">
                                    <label class="form-lebel">CATATAN</label>
                                    <textarea class="form-control" name="catatan" value="{{ $tuntutan->catatan }}"> </textarea>

                                </div>
                            </div>
                        </div>

                        </div>

                            </div>
                        </div>
                        <div class="card-footer">

                            <a href="{{ route('tuntutan.edit', $tuntutan->id) }}" class="btn btn-primary">HANTAR</button>
                            <a href="{{ route('tuntutan.print', $tuntutan->id) }}" class="btn btn-warning">CETAK</a>
                            
                            {{-- Paparkan butang cetak jika ada status tertentu
                            @if ($tuntutan->status == Tuntutan::STATUS_BAYARAN_SELESAI)
                            <a href="{{ route('tuntutan.print', $tuntutan->id) }}" class="btn btn-warning">CETAK</a>
                            @endif
                             --}}
                        </div> 
                    </div>
                </form>

            </div>
        </div>

    </div>
</section>

@endsection

resources/views/tuntutan/create.blade.php
@extends('layouts.induk')
@section('content-utama')

<link href="/chosen_v1.8.7/chosen.css" type="text/css" rel="stylesheet">
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0">Daftar Tuntutan</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
            <li class="breadcrumb-item active">Daftar Tuntutan</li>
            </ol>
        </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<section class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">

                <form method="POST" action="{{ route('tuntutan.store') }}">
                    @csrf
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label class="form-label">NO. RUJUKAN FAIL TUNTUTAN</label>
                                        <input type="text" class="form-control @error('no_fail') is-invalid @enderror" name="no_rujukan_fail" value="{{ old('no_fail') }}" required>
                                        @error('no_fail')
                                        <div class="invalid-feedback">
                                            {{ $message }}.
                                        </div>
                                        @enderror
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label class="form-label">NAMA PEMBEKAL</label>
                                        {{ Form::select('pp_id', $senaraiPembekal, '', ['id' => 'pembekal_id', 'class' => 'form-control']) }}
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label class="form-label">TARIKH TUNTUTAN</label>
                                        <input type="date" class="form-control @error('tarikh_tuntutan') is-invalid @enderror" name="tkh_tuntutan">
                                        @error('tarikh_tuntutan')
                                        <div class="invalid-feedback">
                                            {{ $message }}.
                                        </div>
                                        @enderror
                                    </div>

                                </div>

                                <div class="col-md-6">

                                    <div class="mb-3">
                                        <label class="form-label">JUMLAH TUNTUTAN (RM)</label>
                                        <input type="number" class="form-control @error('jumlah_tuntutan') is-invalid @enderror" name="jum_tuntutan" min="0.01" step="0.01">
                                        @error('jumlah_tuntutan')
                                        <div class="invalid-feedback">
                                            {{ $message }}.
                                        </div>
                                        @enderror
                                    </div>

                                </div>

                            </div>

                            <div class="row">

                                <div class="col-md-12">

                                    <div class="mb-3">
                                        <label class="form-label">PANEL PENYEMAK</label>
                                        <select name="penyemak_id" class="form-control">
                                            @foreach ($senaraiPanel as $panel)
                                                <option value="{{ $panel->id }}" {{ old('panel') == $panel->id ? 'selected="selected"' : NULL }}>{{ $panel->nama }}</option>
                                            @endforeach
                                        </select>
                                        @error('user_id')
                                        <div class="invalid-feedback">
                                            {{ $message }}.
                                        </div>
                                        @enderror
                                    </div>

                                </div>

                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">DAFTAR</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
@endsection

@push('script_extra')
    <script src="/chosen_v1.8.7/chosen.jquery.js"></script>
    <script>
        $('#pembekal_id').chosen();
    </script>
@endpush

resources/views/tuntutan/datatables-tindakan.blade.php
<a href="{{ route('tuntutan.show', $tuntutan->id) }}" class="btn btn-info">DETAIL</a>

{{-- <!-- Button trigger modal -->
<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modal-delete-{{ $tuntutan->id }}">
    HAPUS
</button>

<!-- Modal -->
<div class="modal fade" id="modal-delete-{{ $tuntutan->id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <form method="POST" action="{{ route('tuntutan.destroy', $tuntutan->id) }}">
        @csrf
        @method('DELETE')
    <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Pengesahan</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            Adakah anda bersetuju untuk menghapuskan data ini?
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CLOSE</button>
        <button type="button" class="btn btn-danger">DELETE</button>
        </div>
    </div>
    </div>
    </form>
</div> --}}

resources/views/tuntutan/listing.blade.php
@extends('layouts.induk')
@section('content-utama')
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Bil</th>
            <th>No rujukan Fail</th>
            <th>Jumlah Tuntutan</th>
            <th>Tarikh Tuntutan</th>
            <th>Jumlah Peruntukan</th>
            <th>Status</th>
            <th>Tindakan</th>
        </tr>
    </thead>
    <tbody>
        @foreach($rows as $row)
        <tr>
            <td></td>
            <td>{{ $row->no_rujukan_fail }}</td>
            <td>{{ $row->jum_tuntutan }}</td>
            <td>{{ $row->tkh_tuntutan }}</td>
            <td>{{ $row->jum_kontrak }}</td>
            <td>{{ $status[$row->status] }}</td>
            <td></td>
        </tr>
        @endforeach
    </tbody>
</table>
@endsection