routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SkimController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\PembekalController;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\TuntutanController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\TuntutanPrintController;

Route::get('/pwd', function() {
    return \Hash::make('1234');
});

Route::redirect('/', '/login');

// Fungsi authentication
Route::get('login', [LoginController::class, 'borangLogin'])->name('login');
Route::post('login', [LoginController::class, 'authenticate'])->name('login.authenticate');

// Ruangan pengguna selepas login
Route::group(['middleware' => 'auth'], function () {

    Route::get('dashboard', fn() => view('dashboard'))->name('dashboard');

    // Module Pengguna
    Route::any('pengguna', [PenggunaController::class, 'paparSenarai'])->name('users.index');
    Route::get('pengguna/{id}/detail', [PenggunaController::class, 'paparDetail'])->name('users.detail');
    Route::get('pengguna/daftar', [PenggunaController::class, 'paparBorangDaftar'])->name('users.create');
    Route::post('pengguna/daftar', [PenggunaController::class, 'terimaDataPendaftaran'])->name('users.store');
    Route::post('pengguna/{id}', [PenggunaController::class, 'paparPengguna'])->name('users.show');
    Route::get('pengguna/{id}/edit', [PenggunaController::class, 'paparBorangEdit'])->name('users.edit');
    Route::get('pengguna/{id}', [PenggunaController::class, 'terimaDataEdit'])->name('users.update');
    Route::delete('pengguna/{id}', [PenggunaController::class, 'hapusData'])->name('users.destroy');

    // Module Pembekal
    Route::get('pembekal', [PembekalController::class, 'paparSenarai'])->name('pembekal.index');
    Route::get('pembekal/daftar', [PembekalController::class, 'paparBorangDaftar'])->name('pembekal.create');
    Route::post('pembekal/daftar', [PembekalController::class, 'terimaDataPendaftaran'])->name('pembekal.store');
    Route::post('pembekal/{id}', [PembekalController::class, 'paparPembekal'])->name('pembekal.show');
    Route::get('pembekal/{id}/edit', [PembekalController::class, 'paparBorangEdit'])->name('pembekal.edit');
    Route::get('pembekal/{id}', [PembekalController::class, 'terimaDataEdit'])->name('pembekal.update');
    Route::delete('pembekal/{id}', [PembekalController::class, 'hapusData'])->name('pembekal.destroy');

    // Module Skim
    Route::get('skim', [SkimController::class, 'paparSenarai'])->name('skim.index');
    Route::get('skim/daftar', [SkimController::class, 'paparBorangDaftar'])->name('skim.create');
    Route::post('skim/daftar', [SkimController::class, 'terimaDataPendaftaran'])->name('skim.store');
    Route::post('skim/{id}', [SkimController::class, 'paparSkim'])->name('skim.show');
    Route::get('skim/{id}/edit', [SkimController::class, 'paparBorangEdit'])->name('skim.edit');
    Route::get('skim/{id}', [SkimController::class, 'terimaDataEdit'])->name('skim.update');
    Route::delete('skim/{id}', [SkimController::class, 'hapusData'])->name('skim.destroy');

    // Module Tuntutan
    Route::post('tuntutan/datatables', [TuntutanController::class, 'datatables'])->name('tuntutan.datatables');
    Route::get('tuntutan/daftar', [TuntutanController::class, 'paparBorangDaftar'])->name('tuntutan.create');
    Route::post('tuntutan/daftar', [TuntutanController::class, 'terimaDataPendaftaran'])->name('tuntutan.store');
    Route::get('tuntutan/{id}/edit', [TuntutanController::class, 'paparBorangEdit'])->name('tuntutan.edit');
   // Route::get('tuntutan/{id}', [TuntutanController::class, 'terimaDataEdit'])->name('tuntutan.update');
    Route::get('tuntutan/{tuntutan}/print', [TuntutanPrintController::class, 'print'])->name('tuntutan.print');

    Route::resource('tuntutan', TuntutanController::class);

    Route::get('logout', [LogoutController::class, 'logout'])->name('logout');

    Route::get('sub-pembekal/{pembekal_id}', [PembekalController::class, 'subPembekal']);

    Route::any('laporan-tuntutan',
    [LaporanController::class, 'tuntutan']);

});

resources/views/layouts/alerts.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@if (session('alert-success'))
<div class="alert alert-success">
    {{ session('alert-success') }}
</div>
@endif


@if (session('alert-error'))
<div class="alert alert-danger">
    {{ session('alert-error') }}
</div>
@endif

resources/views/layouts/footer.blade.php
<footer class="main-footer">
  <strong>Hak Cipta Terpelihara LPP.</strong>
  All rights reserved.
  <div class="float-right d-none d-sm-inline-block">
    <b>Version</b> 3.2.0
  </div>
</footer>

resources/views/layouts/induk.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ config('app.name') }}</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('themes/adminlte') }}/plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{{ asset('themes/adminlte') }}/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="{{ asset('themes/adminlte') }}/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{{ asset('themes/adminlte') }}/plugins/jqvmap/jqvmap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('themes/adminlte') }}/dist/css/adminlte.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{ asset('themes/adminlte') }}/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{{ asset('themes/adminlte') }}/plugins/daterangepicker/daterangepicker.css">
  <!-- summernote -->
  <link rel="stylesheet" href="{{ asset('themes/adminlte') }}/plugins/summernote/summernote-bs4.min.css">

    @yield('kod_css')

</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="{{ asset('themes/adminlte') }}/dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
  </div>

  <!-- Navbar -->
  @include('layouts.navbar')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  @include('layouts.sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    @include('layouts.alerts')
    @yield('content-utama')
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  @include('layouts.footer')

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{ asset('themes/adminlte') }}/plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('themes/adminlte') }}/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{ asset('themes/adminlte') }}/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- ChartJS -->
<script src="{{ asset('themes/adminlte') }}/plugins/chart.js/Chart.min.js"></script>
<!-- Sparkline -->
<script src="{{ asset('themes/adminlte') }}/plugins/sparklines/sparkline.js"></script>
<!-- JQVMap -->
<script src="{{ asset('themes/adminlte') }}/plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="{{ asset('themes/adminlte') }}/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('themes/adminlte') }}/plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="{{ asset('themes/adminlte') }}/plugins/moment/moment.min.js"></script>
<script src="{{ asset('themes/adminlte') }}/plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('themes/adminlte') }}/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="{{ asset('themes/adminlte') }}/plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="{{ asset('themes/adminlte') }}/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="{{ asset('themes/adminlte') }}/dist/js/adminlte.js"></script>


@stack('script_extra')

</body>
</html>

resources/views/layouts/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="{{ route('dashboard') }}" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="#" class="nav-link">Contact</a>
    </li>
  </ul>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Navbar Search -->
    <li class="nav-item">
      <a class="nav-link" data-widget="navbar-search" href="#" role="button">
        <i class="fas fa-search"></i>
      </a>
      <div class="navbar-search-block">
        <form class="form-inline">
          <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
              <button class="btn btn-navbar" type="submit">
                <i class="fas fa-search"></i>
              </button>
              <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                <i class="fas fa-times"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>

    <!-- Messages Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-comments"></i>
        <span class="badge badge-danger navbar-badge">3</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="{{ asset('themes/adminlte') }}/dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Brad Diesel
                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">Call me whenever you can...</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="{{ asset('themes/adminlte') }}/dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                John Pierce
                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">I got your message bro</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="{{ asset('themes/adminlte') }}/dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Nora Silvester
                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">The subject goes here</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
      </div>
    </li>
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge">15</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-item dropdown-header">15 Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-envelope mr-2"></i> 4 new messages
          <span class="float-right text-muted text-sm">3 mins</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-users mr-2"></i> 8 friend requests
          <span class="float-right text-muted text-sm">12 hours</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-file mr-2"></i> 3 new reports
          <span class="float-right text-muted text-sm">2 days</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="fullscreen" href="#" role="button">
        <i class="fas fa-expand-arrows-alt"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="control-sidebar" data-controlsidebar-slide="true" href="#" role="button">
        <i class="fas fa-th-large"></i>
      </a>
    </li>
  </ul>
</nav>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
<!-- Brand Logo -->
<a href="/" class="brand-link">
    <img src="{{ asset('themes/adminlte') }}/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light">{{ config('app.name')}}</span>
</a>

<!-- Sidebar -->
<div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
    <div class="image">
        <img src="{{ asset('themes/adminlte') }}/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
    </div>
    <div class="info">
        <a href="#" class="d-block">{{ auth()->user()->nama }}</a>
    </div>
    </div>

    <!-- SidebarSearch Form -->
    <div class="form-inline">
    <div class="input-group" data-widget="sidebar-search">
        <input class="form-control form-control-sidebar" type="search" placeholder="Carian" aria-label="Carian">
        <div class="input-group-append">
        <button class="btn btn-sidebar">
            <i class="fas fa-search fa-fw"></i>
        </button>
        </div>
    </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                with font-awesome or any other icon font library -->

            <li class="nav-item menu-open">
                <a href="{{ route('dashboard') }}" class="nav-link active">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    <p>
                    Dashboard
                    </p>
                </a>
            </li>

            @if(auth()->user()->hasAnyPermission(['superadmin.all.areas', 'users.view']))
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-users"></i>
                    <p>
                    Pengguna
                    <i class="fas fa-angle-left right"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{{ route('users.index') }}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Senarai</p>
                        </a>
                    </li>
                    @if(auth()->user()->hasAnyPermission(['superadmin.all.areas', 'users.create']))
                    <li class="nav-item">
                        <a href="{{ route('users.create') }}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Daftar</p>
                        </a>
                    </li>
                    @endif
                </ul>
            </li>
            @endif

            @if(auth()->user()->hasAnyPermission(['superadmin.all.areas', 'skim.view']))
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-folder"></i>
                    <p>
                    Program/Skim
                    <i class="fas fa-angle-left right"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{{ route('skim.index') }}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Senarai</p>
                        </a>
                    </li>
                    @if(auth()->user()->hasAnyPermission(['superadmin.all.areas', 'skim.create']))
                    <li class="nav-item">
                        <a href="{{ route('skim.create') }}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Tambah</p>
                        </a>
                    </li>
                    @endif
                </ul>
            </li>
            @endif

            @if(auth()->user()->hasAnyPermission(['superadmin.all.areas', 'pembekal.view']))
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-user"></i>
                    <p>
                    Pembekal
                    <i class="fas fa-angle-left right"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{{ route('pembekal.index') }}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Senarai</p>
                        </a>
                    </li>
                    @if(auth()->user()->hasAnyPermission(['superadmin.all.areas', 'pembekal.create']))
                    <li class="nav-item">
                        <a href="{{ route('pembekal.create') }}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Daftar</p>
                        </a>
                    </li>
                    @endif
                </ul>
            </li>
            @endif

            @if(auth()->user()->hasAnyPermission(['superadmin.all.areas', 'tuntutan.view',]))
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-edit"></i>
                    <p>
                    Tuntutan
                    <i class="fas fa-angle-left right"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{{ route('tuntutan.index') }}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Senarai</p>
                        </a>
                    </li>
                    @if(auth()->user()->hasAnyPermission(['superadmin.all.areas', 'tuntutan.create']))
                    <li class="nav-item">
                        <a href="{{ route('tuntutan.create') }}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Tambah</p>
                        </a>
                    </li>
                    @endif
                </ul>
            </li>
            @endif

            @if(auth()->user()->hasAnyPermission(['superadmin.all.areas', 'peranan.view']))
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-edit"></i>
                    <p>
                    Peranan
                    <i class="fas fa-angle-left right"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{{ route('tuntutan.index') }}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Senarai</p>
                        </a>
                    </li>
                    @if(auth()->user()->hasAnyPermission(['superadmin.all.areas', 'tuntutan.create']))
                    <li class="nav-item">
                        <a href="{{ route('tuntutan.create') }}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Tambah</p>
                        </a>
                    </li>
                    @endif
                </ul>
            </li>
            @endif

            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-file"></i>
                    <p>
                    Laporan
                    <i class="fas fa-angle-left right"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Statistik</p>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="nav-item">
                <a href="{{ route('logout') }}" class="nav-link">
                    <i class="nav-icon fas fa-arrow-right"></i>
                    <p>
                    Log Keluar
                    </p>
                </a>
            </li>

        </ul>
    </nav>
    <!-- /.sidebar-menu -->
</div>
<!-- /.sidebar -->
</aside>